### PR TITLE
Add menu item to hide icon in the system menu bar

### PR DESCRIPTION
**Pull request by Stuk**
I like to keep my menu bar clean, and so I've added functionality to hide the icon. It can be shown again by relaunching the application.

screen shot 2018-01-01 at 4 08 46 pm

Happy to make any changes you'd like :) Thanks for the great tool!

### CODE REVIEW

**Comment by bjarkebech** [comment]
+1

**Comment by bjarkebech** [comment]
@archagon thoughts on implementing this? would be a great addition

**Comment by archagon** [comment]
👍 Good stuff! Will add to the next release, just a bit busy with other stuff at the moment.

**Comment by moritzgloeckl** [comment]
@archagon Would be cool if you'd merge this :) 👍

**Comment by Stuk** [comment]
Thank you!

**Pull request merged**
